features/clean ups
open-power/pdbg pull request #60
Opened 2021-11-15 00:55 UTC by iamjpn

2021-11-16 08:03 UTC, amitay requested changes
First patch requires a bit of re-work.

2021-11-16 08:03 UTC, amitay commented on src/main.c
> +bool cpus_parse(int args[], int arg_count)
Please use `static` declaration for all local functions.

2021-11-22 00:52 UTC, iamjpn commented on src/main.c
> +
`pir_map()` now uses `pdbg_get_proc()`. So we need to have to have `pdbg_proc` set before we do `cpus_parse()`.
`parse_options()` is called before `pdbg_targets_init()`, etc so at that time `pdbg_proc` is not finalized.
That is why it had to be moved out of `parse_options()` into `main()`.

2021-11-23 03:37 UTC, amitay commented
Merged.

2021-11-23 03:37 UTC, closed without merging