POZ: cater for additional requirements to parse SBE FFDC data
open-power/pdbg pull request #92
Opened 2024-03-26 03:37 UTC by devenrao

1) Modify sbe chip-op operation to read FFDC data for chip-op success case so as to get FFDC data from SBE for any earlier or internal SBE failure

2) As SBE now caters for multiple FFDC packets increase the size of the memory allocated by pdbg to read the FFDC data to 32KB.

2024-03-26 05:02 UTC, Swarnendu-R-C requested changes
In the first commit message the description text should start with capital `T` i.e.; `to cater for...` to `To cater for...` (A typo only I guess). Otherwise looks good to me

2024-03-26 06:03 UTC, deepakala-k commented on libsbefifo/operation.c
> +	buflen = (*out_len + 0x8000 + 3) & ~(uint32_t)3;
Is there a challenge or overhead in creating a const variable for 0x8000 like SBEFIFO_MAX_FFDC_SIZE?  though we have added a comment with the same value?

2024-04-03 07:19 UTC, Swarnendu-R-C reviewed
A small suggestion

2024-04-03 07:19 UTC, Swarnendu-R-C commented on libsbefifo/operation.c
> +static const uint16_t SBEFIFO_MAX_FFDC_SIZE = 0x8000;
make it constexpr for better compiler optimization by

2024-04-10 04:54 UTC, dhruvibm approved these changes

2024-04-10 05:55 UTC, Swarnendu-R-C approved these changes

2024-04-16 08:45 UTC, merged